"""A persisted queued/running scheduler sweep is not auto-resumed at boot (#16).

Sweeps are read-only and regenerated by the scheduler; resuming one at startup
contends with the vault opens. Real rehydrate functions and real sidecars; only
the job runners are stand-ins (the code under test is the rehydrate path).
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from types import SimpleNamespace

import pytest

from okto_neuron.server import _ingest_queue, _jobs, _scheduler
from okto_neuron.server._ingest_queue import IngestItem

SWEEPS = sorted(_scheduler.SWEEP_KINDS)
REASON = "interrupted by process restart; not auto-resumed (scheduler regenerates sweeps)"


def _state(root: Path) -> SimpleNamespace:
    return SimpleNamespace(
        vault_path=root,
        curation_jobs=[],
        curation_worker_active=False,
        curation_worker_task=None,
        draining=False,
        shutting_down=False,
        ingest_queue=[],
    )


@pytest.fixture(autouse=True)
def _clean_registry():
    saved = dict(_jobs._REGISTRY)
    _jobs._REGISTRY.clear()
    yield
    _jobs._REGISTRY.clear()
    _jobs._REGISTRY.update(saved)


def _persist_job(root: Path, kind: str, status: str, **params) -> _jobs.CurationJob:
    state = _state(root)
    job = _jobs.new_job(kind, params=params or None)
    job.status = status
    if status == "running":
        job.started_at = 123.0
        job.progress = "proposing"
    state.curation_jobs = [job]
    _jobs.persist(state)
    return job


def test_sweep_kinds_match_scheduler() -> None:
    assert _jobs._SWEEP_KINDS_NOT_RESUMED == _scheduler.SWEEP_KINDS
    assert not _jobs._SWEEP_KINDS_NOT_RESUMED & _jobs._NON_RESUMABLE_ON_RESTART_KINDS


@pytest.mark.parametrize("status", ["running", "queued"])
@pytest.mark.parametrize("kind", SWEEPS)
def test_persisted_sweep_becomes_terminal_error(tmp_path: Path, kind: str, status: str) -> None:
    root = tmp_path / "vault"
    job = _persist_job(root, kind, status)

    fresh = _state(root)
    _jobs.rehydrate_jobs(fresh)

    (restored,) = fresh.curation_jobs
    assert restored.id == job.id
    assert restored.status == "error"
    assert restored.progress == "error"
    assert restored.error == REASON
    assert restored.finished_at is not None
    assert restored.started_at == job.started_at
    durable = json.loads(_jobs.jobs_path(fresh).read_text(encoding="utf-8"))
    assert durable["jobs"][0]["status"] == "error"
    assert durable["jobs"][0]["error"] == REASON


@pytest.mark.parametrize("kind", SWEEPS)
def test_worker_never_starts_a_swept_job(tmp_path: Path, kind: str) -> None:
    calls: list[str] = []
    _jobs.register_runner(kind, lambda s, j: calls.append(j.id) or {}, writes=False)
    root = tmp_path / "vault"
    _persist_job(root, kind, "running")
    fresh = _state(root)
    _jobs.rehydrate_jobs(fresh)

    async def go() -> None:
        _jobs.ensure_worker(fresh)
        task = fresh.curation_worker_task
        if task is not None:
            await asyncio.wait_for(task, 10)

    asyncio.run(go())
    assert calls == []
    assert [j.status for j in fresh.curation_jobs] == ["error"]


def test_resumable_non_sweep_kind_still_resumes(tmp_path: Path) -> None:
    calls: list[str] = []
    _jobs.register_runner("reconcile-apply", lambda s, j: calls.append(j.id) or {}, writes=False)
    root = tmp_path / "vault"
    job = _persist_job(root, "reconcile-apply", "running")
    fresh = _state(root)
    _jobs.rehydrate_jobs(fresh)

    (restored,) = fresh.curation_jobs
    assert restored.status == "queued"
    assert restored.started_at is None
    assert restored.error is None

    async def go() -> None:
        _jobs.ensure_worker(fresh)
        await asyncio.wait_for(fresh.curation_worker_task, 10)

    asyncio.run(go())
    assert calls == [job.id]
    assert fresh.curation_jobs[0].status == "done"


@pytest.mark.parametrize("kind", sorted(_jobs._NON_RESUMABLE_ON_RESTART_KINDS))
def test_non_resumable_kinds_unchanged(tmp_path: Path, kind: str) -> None:
    root = tmp_path / "vault"
    _persist_job(root, kind, "running")
    fresh = _state(root)
    _jobs.rehydrate_jobs(fresh)
    (restored,) = fresh.curation_jobs
    assert restored.status == "error"
    assert "submit a new job explicitly" in (restored.error or "")


def test_queued_non_sweep_stays_queued(tmp_path: Path) -> None:
    root = tmp_path / "vault"
    _persist_job(root, "reconcile-apply", "queued")
    fresh = _state(root)
    _jobs.rehydrate_jobs(fresh)
    assert fresh.curation_jobs[0].status == "queued"


@pytest.mark.parametrize("status", ["done", "error"])
def test_terminal_sweeps_untouched(tmp_path: Path, status: str) -> None:
    root = tmp_path / "vault"
    job = _persist_job(root, "detect-drift", status)
    before = _jobs.jobs_path(_state(root)).read_text(encoding="utf-8")
    fresh = _state(root)
    _jobs.rehydrate_jobs(fresh)
    (restored,) = fresh.curation_jobs
    assert restored.status == status
    assert restored.error == job.error
    assert restored.finished_at == job.finished_at
    assert _jobs.jobs_path(fresh).read_text(encoding="utf-8") == before


def test_info_line_counts_swept_jobs(tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
    root = tmp_path / "myvault"
    state = _state(root)
    state.curation_jobs = [
        _jobs.new_job("reconcile-propose"),
        _jobs.new_job("detect-drift"),
        _jobs.new_job("reconcile-apply"),
    ]
    state.curation_jobs[0].status = "running"
    _jobs.persist(state)

    fresh = _state(root)
    with caplog.at_level(logging.INFO, logger="okto_neuron.server.jobs"):
        _jobs.rehydrate_jobs(fresh)
    lines = [r.getMessage() for r in caplog.records if "sweep jobs not resumed" in r.getMessage()]
    assert lines == ["2 sweep jobs not resumed after restart for myvault"]

    caplog.clear()
    again = _state(root)
    with caplog.at_level(logging.INFO, logger="okto_neuron.server.jobs"):
        _jobs.rehydrate_jobs(again)
    assert not [r for r in caplog.records if "sweep jobs not resumed" in r.getMessage()]


def test_no_info_line_without_sweeps(tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
    root = tmp_path / "vault"
    _persist_job(root, "reconcile-apply", "running")
    with caplog.at_level(logging.INFO, logger="okto_neuron.server.jobs"):
        _jobs.rehydrate_jobs(_state(root))
    assert not [r for r in caplog.records if "sweep jobs not resumed" in r.getMessage()]


def test_second_rehydrate_is_idempotent(tmp_path: Path) -> None:
    root = tmp_path / "vault"
    _persist_job(root, "predicate-propose", "running")
    first = _state(root)
    _jobs.rehydrate_jobs(first)
    snapshot = _jobs.jobs_path(first).read_text(encoding="utf-8")
    second = _state(root)
    _jobs.rehydrate_jobs(second)
    assert _jobs.jobs_path(second).read_text(encoding="utf-8") == snapshot
    assert second.curation_jobs[0].error == REASON
    assert second.curation_jobs[0].finished_at == first.curation_jobs[0].finished_at


def test_linked_d8_ingest_outcome_is_failed_and_persisted(tmp_path: Path) -> None:
    root = tmp_path / "vault"
    state = _state(root)
    job = _jobs.new_job(
        "reconcile-propose",
        params={"trigger": "verified_file_commit", "ingest_item_ids": ["ingest-1"]},
    )
    job.status = "running"
    state.curation_jobs = [job]
    _jobs.persist(state)
    state.ingest_queue = [
        IngestItem(
            id="ingest-1",
            name="book.md",
            path="/book.md",
            status="done",
            outcome={
                "quality": "complete",
                "cross_document_reconciliation": {
                    "state": "scheduled",
                    "job_id": job.id,
                    "trigger": "verified_file_commit",
                    "coalesced": False,
                },
            },
        ),
        IngestItem(  # a retried item whose link points at a different job is left alone
            id="ingest-2",
            name="b.md",
            path="/b.md",
            status="done",
            outcome={"cross_document_reconciliation": {"state": "scheduled", "job_id": "other"}},
        ),
    ]
    _ingest_queue.persist(state)

    # Real startup order: ingest queue first, then the jobs.
    fresh = _state(root)
    _ingest_queue.rehydrate_queue(fresh)
    _jobs.rehydrate_jobs(fresh)

    item = fresh.ingest_queue[0]
    assert item.status == "done"  # the graph commit itself stays done
    linked = item.outcome["cross_document_reconciliation"]
    assert linked["state"] == "failed"
    assert linked["job_id"] == job.id
    assert linked["error"] == REASON
    assert fresh.ingest_queue[1].outcome["cross_document_reconciliation"]["state"] == "scheduled"

    on_disk = json.loads(_ingest_queue.history_path(fresh).read_text(encoding="utf-8"))
    persisted = {i["id"]: i for i in on_disk["items"]}
    assert persisted["ingest-1"]["outcome"]["cross_document_reconciliation"]["state"] == "failed"
    assert persisted["ingest-1"]["outcome"]["cross_document_reconciliation"]["error"] == REASON
