"""Install-footprint regression checks for optional wheel installs."""

import os
import pathlib
import shutil
import subprocess
import sys
import venv

import pytest


pytestmark = [pytest.mark.footprint, pytest.mark.slow]
WHEEL_ENV = "OKTO_NEURON_WHEEL"
RUNTIME_EXTRAS = "serve,litellm"
# Full warmed runtime (including Python bytecode generated by the import check)
# measured 364 MB on macOS arm64 and 421 MB on Linux x86_64 when this ceiling
# was first set. Unpinned upstream releases have since grown it: in September
# 2026 hosted CI (ubuntu-latest) measured 460.7 MB for the 0.3.0 wheel, and a
# python:3.12-slim x86_64 container measured 457.9 MB for 0.3.0 and 457.7 MB
# for the published 0.2.0 wheel, so the growth is in dependencies, not in this
# package. The ceiling keeps under 7% headroom above the hosted CI result.
# The old 300 MB limit had only passed because the nonexistent [local] extra
# silently installed the core package alone.
MAX_SITE_PACKAGES_BYTES = 490_000_000


def _site_packages_size(site_packages: pathlib.Path) -> int:
    return sum(path.stat().st_size for path in site_packages.rglob("*") if path.is_file())


def test_install_footprint_ceiling(tmp_path: pathlib.Path) -> None:
    wheel = os.environ.get(WHEEL_ENV)
    if not wheel:
        pytest.skip("set OKTO_NEURON_WHEEL=/path/to/wheel to run")

    venv_dir = tmp_path / "v"
    venv.EnvBuilder(with_pip=True).create(venv_dir)

    scripts = venv_dir / ("Scripts" if os.name == "nt" else "bin")
    pip = scripts / ("pip.exe" if os.name == "nt" else "pip")
    python = scripts / ("python.exe" if os.name == "nt" else "python")
    if shutil.which(str(pip)) is None:
        pytest.fail(f"pip missing at {pip} on {sys.platform}")

    subprocess.run(
        [str(pip), "install", f"{wheel}[{RUNTIME_EXTRAS}]"],
        check=True,
        timeout=600,
    )
    subprocess.run(
        [str(python), "-c", "import fastembed, fastmcp, ladybug, litellm"],
        check=True,
        timeout=60,
    )

    site_packages = next(venv_dir.rglob("site-packages"))
    size = _site_packages_size(site_packages)
    print(f"site-packages {size} bytes ({size / 1_000_000:.1f} MB)")
    assert size < MAX_SITE_PACKAGES_BYTES, (
        f"site-packages {size} exceeds {MAX_SITE_PACKAGES_BYTES} byte ceiling"
    )
