"""Vectors-only re-embed: copy a graph into a fresh store, recomputing vectors.

The expensive part of ingest is LLM extraction; the embeddings are cheap. When the
embedding model (or its width) changes, we don't need to re-extract — we can replay
the EXISTING graph's stored text through the new embedder. Because the Ladybug
vector column is fixed-width, a width change can't be applied in place; the caller
bootstraps a fresh graph at the new width and this module copies nodes (recomputing
vectors) then edges into it.

Invariants this module upholds:

- **Per-type embed text.** A stored Claim was minted with ``title == content ==
  rel_text`` and embedded as the bare ``rel_text``; primitives embed
  ``f"{title}\\n{content}"``. Recomputing through one uniform formula would embed
  Claim text twice and shift every Claim cosine. We route every node through
  :func:`okto_neuron.companion.embedding_text_for`, the SAME helper both write sites
  use, so a recompute reproduces the original vector exactly (same model/width).
- **Preserve ``None`` embeddings.** Some nodes (e.g. Blocks/Documents) carry no
  vector; fabricating one would make them newly retrievable and change recall. A
  node with ``embedding is None`` is copied verbatim.
- **Nodes before edges.** ``add_edge`` requires both endpoints to exist, so all
  nodes are written before any edge. Edge ``created_at`` is regenerated by the
  store writer (it is not selected by ``list_edges``); this is accepted.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

    from okto_neuron.core.schema import Edge, Node
    from okto_neuron.embed import EmbeddingProvider
    from okto_neuron.store.ladybug import LadybugStore
    from okto_neuron.store.protocol import GraphStore


def copy_graph_reembedding(
    nodes: "Sequence[Node]",
    edges: "Sequence[Edge]",
    tmp_store: "LadybugStore",
    embedder: "EmbeddingProvider",
    *,
    batch_size: int = 32,
    max_concurrent_batches: int = 1,
    embedding_settings: "Callable[[], tuple[int, int]] | None" = None,
    progress: "Callable[[int, int], None] | None" = None,
) -> dict[str, int]:
    """Write ``nodes`` (recomputing vectors) then ``edges`` into ``tmp_store``.

    ``nodes``/``edges`` are read from the live graph BEFORE ``tmp_store`` is
    bootstrapped (so the live handle is already released by swap time). ``progress``
    reports completed embedding inputs plus nodes that need no vector. Returns a
    small stats dict for the caller's progress/state file.
    """
    # Lazy import: companion is a heavy module that imports the store layer, so a
    # top-level import here would risk a cycle. At call time everything is loaded.
    from okto_neuron.companion import embedding_text_for
    from okto_neuron.embed import embed_in_batches

    total = len(nodes)
    embeddable = [node for node in nodes if node.embedding is not None]
    copied = total - len(embeddable)
    if progress is not None and copied:
        progress(copied, total)

    def _embedding_progress(done: int, _embedding_total: int) -> None:
        if progress is not None:
            progress(copied + done, total)

    vectors = embed_in_batches(
        embedder,
        [embedding_text_for(node) for node in embeddable],
        batch_size=batch_size,
        max_concurrent_batches=max_concurrent_batches,
        settings=embedding_settings,
        progress=_embedding_progress,
    )
    vector_by_id = {node.id: vector for node, vector in zip(embeddable, vectors, strict=True)}

    for node in nodes:
        if node.embedding is None:
            tmp_store.add_node(node)
        else:
            tmp_store.add_node(node.model_copy(update={"embedding": vector_by_id[node.id]}))

    for edge in edges:
        tmp_store.add_edge(edge)

    return {
        "nodes": len(nodes),
        "edges": len(edges),
        "recomputed": len(embeddable),
        "copied": copied,
    }


def copy_graph_canonicalizing(
    nodes: "Sequence[Node]",
    edges: "Sequence[Edge]",
    equivalence: "dict[str, str] | None",
    dst_store: "GraphStore",
    *,
    predicate_aliases: "dict[str, str] | None" = None,
    inverse_aliases: "dict[str, str] | None" = None,
) -> dict[str, int]:
    """Deterministically materialize an off-graph equivalence fold (ADR 0009 P3 heal)
    into the topology of a FRESH graph — NO LLM, NO embedder.

    This is the heal counterpart to :func:`copy_graph_reembedding`: instead of
    replaying text through a new embedder, it copies the EXISTING graph verbatim
    (vectors included) while folding every variant node onto its canonical. It is the
    same transform the read-time fold (``_curation.fold_graph``) applies to a query
    view, but written PERMANENTLY into a new graph file the daemon then swaps in.

    ``equivalence`` is ``member_id -> canonical_id`` (canonical maps to itself), as
    produced by ``AuthorityIndex.equivalence_map`` via ``Vault._equivalence_map``.
    ``predicate_aliases`` is ``predicate -> canonical`` for exact-match predicate
    folds. ``inverse_aliases`` is ``predicate -> canonical inverse``; matching
    entity-object claims swap ``S_id``/``O_id`` and matching direct edges swap
    ``src``/``dst`` before the ADR 0016 semantic-triple collapse. ``None``/empty
    maps => a verbatim copy (idempotent — a re-heal on an already-collapsed graph is
    a no-op fold).

    Mechanics (mirrors fold_graph.repr_in_view so the materialized graph EQUALS the
    folded view recall/Browse already show):

    1. SURVIVING SET / NODE DROP. ``repr_for(nid)`` is the id ``nid`` collapses to
       WITHIN the surviving set: its canonical when that canonical is actually
       present, else itself (the stale-authority guard — without it an edge would
       remap to a non-existent node = dangling). KEEP a node iff it represents
       itself (it is canonical, or its canonical is absent). DROP variant nodes whose
       canonical survives. Kept nodes are added FIRST (``add_edge`` needs both
       endpoints present). Nodes are copied VERBATIM — ``embedding`` preserved as-is
       (merging a variant does not change the canonical's text, so its vector is
       still valid; there is NO embedder in the heal path).

    2. CLAIM FACET REMAP + SEMANTIC RE-KEY. A Claim node carries ``S_id``/``O_id`` in ``facets``
       (companion dumps ``claim.model_dump()`` there). For a kept Claim, remap
       ``S_id`` and (when present and not None — literal-object claims carry
       ``O_id == None``) ``O_id`` through ``repr_for`` so the facets stay consistent
       with the remapped ``rdf:subject``/``rdf:object`` edges. Then collapse Claim
       nodes that now assert the same semantic triple ``(S_id, P, O_id|O_literal)``:
       keep the first Claim's payload, write it under the semantic Claim id, drop
       later mention-scoped ids, and merge their integer ``corroborations`` facets
       (missing = 1). Provenance ids
       (document/block/extraction-activity/agent) are NEVER touched — they point at
       Documents/Blocks/Activities/Agents, never merged entities.

    3. EDGE REMAP + SELF-LOOP DROP + CONTENT-ADDRESSED DEDUP. For each edge: remap
       ``src``/``dst`` through ``repr_for``; when either endpoint is an old Claim
       id, remap it onto the semantic Claim id; skip if an endpoint did not survive;
       skip self-loops the collapse creates (a variant→canonical edge of a now-
       reflexive type); recompute the content-addressed id
       ``sha256_hex("edge", src, type, dst)``; skip ids already emitted (dedup).
       This is ADR-0007-SAFE because it is a FRESH append-only build whose complete
       topology can be verified before swap.

    Returns a stats dict the caller threads into its progress/state file.
    """
    from okto_neuron.consolidate._claim_identity import semantic_claim_id
    from okto_neuron.ingest.markdown import sha256_hex

    equivalence = equivalence or {}
    predicate_aliases = predicate_aliases or {}
    inverse_aliases = inverse_aliases or {}
    inverse_order = {predicate: index for index, predicate in enumerate(inverse_aliases)}
    present_ids = {n.id for n in nodes}
    predicates_folded = 0
    claims_inverse_rewritten = 0

    def repr_for(nid: str) -> str:
        canonical = equivalence.get(nid, nid)
        return canonical if canonical in present_ids else nid

    def inverse_canonical(predicate: str) -> str | None:
        canonical = inverse_aliases.get(predicate)
        if canonical is None:
            return None
        if inverse_aliases.get(canonical) == predicate:
            # PredicateAliasIndex.inverse_map() exposes confirmed inverse pairs in
            # both directions. The first direction is the ledger subject -> object
            # orientation; using only that direction keeps the object predicate as
            # the materialized canonical instead of flipping canonical facts back.
            if inverse_order.get(predicate, 0) > inverse_order.get(canonical, 0):
                return None
        return canonical

    def exact_predicate(predicate: str) -> str:
        return predicate_aliases.get(predicate, predicate)

    def fold_predicate(predicate: str) -> tuple[str, bool]:
        canonical = inverse_canonical(predicate)
        if canonical is not None:
            return canonical, True
        return exact_predicate(predicate), False

    def claim_identity_updates(
        node: "Node",
    ) -> tuple[str, dict[str, object], bool] | None:
        facets = node.facets or {}
        subject = facets.get("S_id")
        predicate = facets.get("P")
        if subject is None or predicate is None:
            return None

        subject_id = repr_for(str(subject))
        raw_predicate = str(predicate)
        object_id = facets.get("O_id")
        if object_id is not None:
            predicate_id, inverse_rewritten = fold_predicate(raw_predicate)
            canonical_object_id = repr_for(str(object_id))
            if inverse_rewritten:
                subject_id, canonical_object_id = canonical_object_id, subject_id
            claim_id = semantic_claim_id(
                subject_id,
                predicate_id,
                object_id=canonical_object_id,
            )
            return (
                claim_id,
                {
                    "id": claim_id,
                    "S_id": subject_id,
                    "P": predicate_id,
                    "O_id": canonical_object_id,
                },
                inverse_rewritten,
            )
        elif facets.get("O_literal") is not None:
            predicate_id = exact_predicate(raw_predicate)
            claim_id = semantic_claim_id(
                subject_id,
                predicate_id,
                literal=facets["O_literal"],
            )
            return (
                claim_id,
                {
                    "id": claim_id,
                    "S_id": subject_id,
                    "P": predicate_id,
                    "O_id": None,
                },
                False,
            )
        else:
            return None

    def claim_corroborations(node: "Node") -> int:
        value = (node.facets or {}).get("corroborations")
        if isinstance(value, int) and not isinstance(value, bool):
            return value
        return 1

    claims_in = 0
    claim_survivors: dict[str, str] = {}
    claim_updates_by_id: dict[str, dict[str, object]] = {}
    claim_group_sizes: dict[str, int] = {}
    claim_corroborations_by_id: dict[str, int] = {}
    claim_to_output: dict[str, str] = {}
    duplicate_claims: set[str] = set()
    entity_titles: dict[str, str] = {
        node.id: node.title for node in nodes if node.type != "Claim" and node.title
    }
    for node in nodes:
        if node.type != "Claim":
            continue
        claims_in += 1
        if repr_for(node.id) != node.id:
            continue
        identity_updates = claim_identity_updates(node)
        if identity_updates is None:
            continue
        claim_id, updates, inverse_rewritten = identity_updates
        raw_predicate = str((node.facets or {}).get("P"))
        if updates.get("P") != raw_predicate:
            predicates_folded += 1
        if inverse_rewritten:
            claims_inverse_rewritten += 1
        claim_to_output[node.id] = claim_id
        claim_updates_by_id[node.id] = updates
        survivor = claim_survivors.get(claim_id)
        if survivor is None:
            claim_survivors[claim_id] = node.id
        else:
            duplicate_claims.add(node.id)
        claim_group_sizes[claim_id] = claim_group_sizes.get(claim_id, 0) + 1
        claim_corroborations_by_id[claim_id] = claim_corroborations_by_id.get(
            claim_id, 0
        ) + claim_corroborations(node)

    surviving: set[str] = set()
    nodes_kept = 0
    nodes_dropped = 0
    claims_kept = 0
    for node in nodes:
        if repr_for(node.id) != node.id or node.id in duplicate_claims:
            nodes_dropped += 1
            continue  # variant or duplicate Claim whose survivor is kept
        output_id = claim_to_output.get(node.id, node.id)
        surviving.add(output_id)
        to_add = node
        facets = node.facets or {}
        node_updates: dict[str, object] = {}
        if output_id != node.id:
            node_updates["id"] = output_id
        if facets:
            updates: dict[str, object] = {}
            if "S_id" in facets and facets["S_id"] is not None:
                updates["S_id"] = repr_for(str(facets["S_id"]))
            if "O_id" in facets and facets["O_id"] is not None:
                updates["O_id"] = repr_for(str(facets["O_id"]))
            if node.id in claim_updates_by_id:
                updates.update(claim_updates_by_id[node.id])
            if node.type == "Claim":
                # The claim title/content embed "S P O" verbatim at mint time;
                # recompose from the (possibly folded/remapped) facets so display
                # strings never drift from the semantic triple.
                merged = {**facets, **updates}
                subject_title = entity_titles.get(repr_for(str(merged.get("S_id") or "")), "")
                predicate = str(merged.get("P") or "")
                object_id = merged.get("O_id")
                object_label = (
                    entity_titles.get(repr_for(str(object_id)), "")
                    if object_id
                    else str(merged.get("O_literal") or "")
                )
                if subject_title and predicate and object_label:
                    display = f"{subject_title} {predicate} {object_label}"
                    if node.title != display:
                        node_updates["title"] = display
                    if node.content and node.content != display:
                        node_updates["content"] = display
            if output_id in claim_group_sizes and claim_group_sizes[output_id] > 1:
                updates["corroborations"] = claim_corroborations_by_id[output_id]
            if updates:
                node_updates["facets"] = {**facets, **updates}
        if node_updates:
            to_add = node.model_copy(update=node_updates)
        dst_store.add_node(to_add)
        nodes_kept += 1
        if node.type == "Claim":
            claims_kept += 1

    seen: set[str] = set()
    edges_kept = 0
    edges_dropped = 0
    self_loops = 0
    dedup_collisions = 0
    for edge in edges:
        edge_type, inverse_rewritten = fold_predicate(str(edge.type))
        if edge_type != str(edge.type):
            predicates_folded += 1
        if str(edge.type) in {"rdf:subject", "rdf:object"} and edge.src in claim_updates_by_id:
            s = claim_to_output.get(edge.src, repr_for(edge.src))
            target_key = "S_id" if str(edge.type) == "rdf:subject" else "O_id"
            target = claim_updates_by_id[edge.src].get(target_key)
            if target is None:
                edges_dropped += 1
                continue
            d = str(target)
        else:
            src = edge.dst if inverse_rewritten else edge.src
            dst = edge.src if inverse_rewritten else edge.dst
            s = claim_to_output.get(src, repr_for(src))
            d = claim_to_output.get(dst, repr_for(dst))
        if s not in surviving or d not in surviving:
            edges_dropped += 1
            continue  # an endpoint was dropped
        if s == d:
            self_loops += 1
            continue  # self-loop the collapse created
        new_id = sha256_hex("edge", s, edge_type, d)
        if new_id in seen:
            dedup_collisions += 1
            continue  # content-addressed dedup (fresh append-only build → skip-safe)
        seen.add(new_id)
        dst_store.add_edge(
            edge.model_copy(update={"src": s, "dst": d, "type": edge_type, "id": new_id})
        )
        edges_kept += 1

    return {
        "nodes_in": len(nodes),
        "nodes_kept": nodes_kept,
        "nodes_dropped": nodes_dropped,
        "claims_in": claims_in,
        "claims_kept": claims_kept,
        "claims_dropped": claims_in - claims_kept,
        "edges_in": len(edges),
        "edges_kept": edges_kept,
        "edges_dropped": edges_dropped,
        "self_loops": self_loops,
        "dedup_collisions": dedup_collisions,
        "predicates_folded": predicates_folded,
        "claims_inverse_rewritten": claims_inverse_rewritten,
    }


__all__ = ["copy_graph_reembedding", "copy_graph_canonicalizing"]
